# https://taskfile.dev

version: '3'

tasks:
  api:setup_test:
    cmds:
      - uv sync --extra test
      - ./scripts/setup_test_db.sh
  api:start:
    env:
      APP_DEBUG: true
    cmd: uv run main.py
  api:migrate:
    cmd: alembic upgrade head
  api:downmigrate:
    cmd: alembic downgrade -1
  api:test:
    cmd: uv run pytest