# https://taskfile.dev

version: '3'

tasks:
  api:start:
    env:
      APP_DEBUG: true
    cmd: uv run main.py
  api:migrate:
    cmd: alembic upgrade head
  api:downmigrate:
    cmd: alembic downgrade -1