// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * CreatePaste
 */
export type CreatePaste = {
    /**
     * Title
     *
     * The title of the paste
     */
    title: string;
    /**
     * Content
     *
     * The content of the paste
     */
    content: string;
    /**
     * The language of the content
     */
    content_language?: PasteContentLanguage;
    /**
     * Expires At
     *
     * The datetime the Paste should expire (None = Never) Note: No guarantee given!
     */
    expires_at?: string | null;
};

/**
 * CreatePasteResponse
 */
export type CreatePasteResponse = {
    /**
     * Id
     *
     * The unique identifier of the paste
     */
    id: string;
    /**
     * Title
     *
     * The title of the paste
     */
    title: string;
    /**
     * Content
     *
     * The content of the paste, possible null if the content couldnt be read.
     */
    content: string | null;
    /**
     * The language of the content
     */
    content_language: PasteContentLanguage;
    /**
     * Expires At
     *
     * The number of hours until the paste expires (0 = never) Note: No guarantee given!
     */
    expires_at?: string | null;
    /**
     * Created At
     *
     * The creation timestamp of the paste
     */
    created_at: string;
    /**
     * Last Updated At
     *
     * The last time the paste was updated (null = never)
     */
    last_updated_at: string | null;
    /**
     * Edit Token
     *
     * The token to edit the paste
     */
    edit_token: string;
    /**
     * Delete Token
     *
     * The token to delete the paste
     */
    delete_token: string;
};

/**
 * EditPaste
 */
export type EditPaste = {
    /**
     * Title
     *
     * The title of the paste
     */
    title?: string | null;
    /**
     * Content
     *
     * The content of the paste
     */
    content?: string | null;
    /**
     * The language of the content
     */
    content_language?: PasteContentLanguage | null;
    /**
     * Expires At
     *
     * The expiration datetime. Explicitly set to null to remove expiration.
     */
    expires_at?: string | Unset | null;
};

/**
 * ErrorResponse
 */
export type ErrorResponse = {
    /**
     * Error
     */
    error: string;
    /**
     * Message
     */
    message: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LegacyPasteResponse
 */
export type LegacyPasteResponse = {
    /**
     * Content
     *
     * The content of the legacy paste, possible null if the content couldnt be read.
     */
    content: string | null;
};

/**
 * PasteContentLanguage
 */
export type PasteContentLanguage = 'plain_text';

/**
 * PasteResponse
 */
export type PasteResponse = {
    /**
     * Id
     *
     * The unique identifier of the paste
     */
    id: string;
    /**
     * Title
     *
     * The title of the paste
     */
    title: string;
    /**
     * Content
     *
     * The content of the paste, possible null if the content couldnt be read.
     */
    content: string | null;
    /**
     * The language of the content
     */
    content_language: PasteContentLanguage;
    /**
     * Expires At
     *
     * The number of hours until the paste expires (0 = never) Note: No guarantee given!
     */
    expires_at?: string | null;
    /**
     * Created At
     *
     * The creation timestamp of the paste
     */
    created_at: string;
    /**
     * Last Updated At
     *
     * The last time the paste was updated (null = never)
     */
    last_updated_at: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * _Unset
 */
export type Unset = {
    [key: string]: unknown;
};

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadyReadyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ready';
};

export type ReadyReadyGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type MetricsMetricsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/metrics';
};

export type MetricsMetricsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetLegacyPastePastesLegacyPasteIdGetData = {
    body?: never;
    path: {
        /**
         * Paste Id
         */
        paste_id: string;
    };
    query?: never;
    url: '/pastes/legacy/{paste_id}';
};

export type GetLegacyPastePastesLegacyPasteIdGetErrors = {
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLegacyPastePastesLegacyPasteIdGetError = GetLegacyPastePastesLegacyPasteIdGetErrors[keyof GetLegacyPastePastesLegacyPasteIdGetErrors];

export type GetLegacyPastePastesLegacyPasteIdGetResponses = {
    /**
     * Successful Response
     */
    200: LegacyPasteResponse;
};

export type GetLegacyPastePastesLegacyPasteIdGetResponse = GetLegacyPastePastesLegacyPasteIdGetResponses[keyof GetLegacyPastePastesLegacyPasteIdGetResponses];

export type DeletePastePastesPasteIdDeleteData = {
    body?: never;
    path: {
        /**
         * Paste Id
         */
        paste_id: string;
    };
    query?: never;
    url: '/pastes/{paste_id}';
};

export type DeletePastePastesPasteIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePastePastesPasteIdDeleteError = DeletePastePastesPasteIdDeleteErrors[keyof DeletePastePastesPasteIdDeleteErrors];

export type DeletePastePastesPasteIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetPasteByUuidPastesPasteIdGetData = {
    body?: never;
    path: {
        /**
         * Paste Id
         */
        paste_id: string;
    };
    query?: never;
    url: '/pastes/{paste_id}';
};

export type GetPasteByUuidPastesPasteIdGetErrors = {
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPasteByUuidPastesPasteIdGetError = GetPasteByUuidPastesPasteIdGetErrors[keyof GetPasteByUuidPastesPasteIdGetErrors];

export type GetPasteByUuidPastesPasteIdGetResponses = {
    /**
     * Successful Response
     */
    200: PasteResponse;
};

export type GetPasteByUuidPastesPasteIdGetResponse = GetPasteByUuidPastesPasteIdGetResponses[keyof GetPasteByUuidPastesPasteIdGetResponses];

export type EditPastePastesPasteIdPutData = {
    body: EditPaste;
    path: {
        /**
         * Paste Id
         */
        paste_id: string;
    };
    query?: never;
    url: '/pastes/{paste_id}';
};

export type EditPastePastesPasteIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EditPastePastesPasteIdPutError = EditPastePastesPasteIdPutErrors[keyof EditPastePastesPasteIdPutErrors];

export type EditPastePastesPasteIdPutResponses = {
    /**
     * Successful Response
     */
    200: PasteResponse;
};

export type EditPastePastesPasteIdPutResponse = EditPastePastesPasteIdPutResponses[keyof EditPastePastesPasteIdPutResponses];

export type GetPasteRawPastesPasteIdRawGetData = {
    body?: never;
    path: {
        /**
         * Paste Id
         */
        paste_id: string;
    };
    query?: never;
    url: '/pastes/{paste_id}/raw';
};

export type GetPasteRawPastesPasteIdRawGetErrors = {
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPasteRawPastesPasteIdRawGetError = GetPasteRawPastesPasteIdRawGetErrors[keyof GetPasteRawPastesPasteIdRawGetErrors];

export type GetPasteRawPastesPasteIdRawGetResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type GetPasteRawPastesPasteIdRawGetResponse = GetPasteRawPastesPasteIdRawGetResponses[keyof GetPasteRawPastesPasteIdRawGetResponses];

export type CreatePastePastesPostData = {
    body: CreatePaste;
    path?: never;
    query?: never;
    url: '/pastes';
};

export type CreatePastePastesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePastePastesPostError = CreatePastePastesPostErrors[keyof CreatePastePastesPostErrors];

export type CreatePastePastesPostResponses = {
    /**
     * Successful Response
     */
    200: CreatePasteResponse;
};

export type CreatePastePastesPostResponse = CreatePastePastesPostResponses[keyof CreatePastePastesPostResponses];
