// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * CreatePaste
 */
export type CreatePaste = {
    /**
     * Title
     *
     * The title of the paste
     */
    title: string;
    /**
     * Content
     *
     * The content of the paste
     */
    content: string;
    /**
     * The language of the content
     */
    content_language?: PasteContentLanguage;
    /**
     * Expires At
     *
     * The datetime the Paste should expire (None = Never) Note: No guarantee given!
     */
    expires_at?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * PasteContentLanguage
 */
export type PasteContentLanguage = 'plain_text';

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetPastePastesPasteIdGetData = {
    body?: never;
    path: {
        /**
         * Paste Id
         */
        paste_id: string;
    };
    query?: never;
    url: '/pastes/{paste_id}';
};

export type GetPastePastesPasteIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPastePastesPasteIdGetError = GetPastePastesPasteIdGetErrors[keyof GetPastePastesPasteIdGetErrors];

export type GetPastePastesPasteIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreatePastePastesPostData = {
    body: CreatePaste;
    path?: never;
    query?: never;
    url: '/pastes';
};

export type CreatePastePastesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePastePastesPostError = CreatePastePastesPostErrors[keyof CreatePastePastesPostErrors];

export type CreatePastePastesPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
