"""Add Delete, Edit tokens and deleted at

Revision ID: 08393764144d
Revises: 7c45e2617d61
Create Date: 2025-12-17 22:00:02.736745

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "08393764144d"
down_revision: str | Sequence[str] | None = "7c45e2617d61"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pastes", sa.Column("edit_token", sa.String(), nullable=True))
    op.add_column("pastes", sa.Column("last_updated_at", sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column("pastes", sa.Column("delete_token", sa.String(), nullable=True))
    op.add_column("pastes", sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pastes", "deleted_at")
    op.drop_column("pastes", "delete_token")
    op.drop_column("pastes", "last_updated_at")
    op.drop_column("pastes", "edit_token")
    # ### end Alembic commands ###
