"""add compression fields

Revision ID: 6c5a2c764fb8
Revises: 0ed6c1042110
Create Date: 2025-12-25 13:23:44.911166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c5a2c764fb8'
down_revision: Union[str, Sequence[str], None] = '0ed6c1042110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pastes', sa.Column('is_compressed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('pastes', sa.Column('original_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pastes', 'original_size')
    op.drop_column('pastes', 'is_compressed')
    # ### end Alembic commands ###
