"""Initial migration

Revision ID: 9e8ceaeba260
Revises: 
Create Date: 2025-12-08 19:06:52.326528

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9e8ceaeba260'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pastes',
                    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
                    sa.Column('title', sa.String(length=255), nullable=False),
                    sa.Column('content_path', sa.String(), nullable=False),
                    sa.Column('content_language', sa.String(), server_default='plain_text', nullable=False),
                    sa.Column('expires_at', sa.DateTime(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('content_size', sa.Integer(), nullable=False),
                    sa.Column('creator_ip', sa.String(), nullable=True),
                    sa.Column('creator_user_agent', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pastes')
    # ### end Alembic commands ###
